/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Controle.ConexaoBD;
import Controller.Controle.ConexaoMotorista;
import Model.Modelo.ModeloMotorista;
import Model.Modelo.ModeloTabela;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;


/**
 *
 * @author MuAwa
 */
public class TelaMotorista extends javax.swing.JFrame {

    ModeloMotorista mod = new ModeloMotorista();
    ConexaoBD conex = new ConexaoBD();
    ConexaoMotorista control = new ConexaoMotorista();
    
    int flag = 0;
    
    public TelaMotorista() {
        initComponents();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        EnviarMotorista = new javax.swing.JButton();
        CodigoMotorista = new javax.swing.JFormattedTextField();
        NomeMotorista = new javax.swing.JFormattedTextField();
        TurnoMotorista = new javax.swing.JComboBox<>();
        CancelarMotorista = new javax.swing.JButton();
        NovoMotorista = new javax.swing.JButton();
        PesquisarMotorista = new javax.swing.JButton();
        CampoPesquisarMotorista = new javax.swing.JTextField();
        EditarMotorista = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));
        jDesktopPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jDesktopPane1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Codigo :  ");

        jLabel2.setText("Nome :");

        jLabel3.setText("Turno : ");

        EnviarMotorista.setText("Enviar");
        EnviarMotorista.setEnabled(false);
        EnviarMotorista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnviarMotoristaActionPerformed(evt);
            }
        });

        CodigoMotorista.setEditable(false);
        CodigoMotorista.setEnabled(false);
        CodigoMotorista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodigoMotoristaActionPerformed(evt);
            }
        });

        NomeMotorista.setEnabled(false);
        NomeMotorista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeMotoristaActionPerformed(evt);
            }
        });

        TurnoMotorista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Matutino", "Vespertino", "Noturno" }));
        TurnoMotorista.setEnabled(false);

        CancelarMotorista.setText("Cancelar");
        CancelarMotorista.setEnabled(false);
        CancelarMotorista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarMotoristaActionPerformed(evt);
            }
        });

        NovoMotorista.setText("Novo");
        NovoMotorista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NovoMotoristaActionPerformed(evt);
            }
        });

        PesquisarMotorista.setText("Pesquisar");
        PesquisarMotorista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesquisarMotoristaActionPerformed(evt);
            }
        });

        CampoPesquisarMotorista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoPesquisarMotoristaActionPerformed(evt);
            }
        });

        EditarMotorista.setText("Editar");
        EditarMotorista.setEnabled(false);
        EditarMotorista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarMotoristaActionPerformed(evt);
            }
        });

        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(EnviarMotorista, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(CodigoMotorista, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(NomeMotorista, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(TurnoMotorista, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(CancelarMotorista, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(NovoMotorista, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(PesquisarMotorista, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(CampoPesquisarMotorista, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(EditarMotorista, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(CampoPesquisarMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(PesquisarMotorista))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(NovoMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EnviarMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EditarMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CancelarMotorista))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CodigoMotorista))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NomeMotorista))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TurnoMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CodigoMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NomeMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(TurnoMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NovoMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EnviarMotorista)
                    .addComponent(EditarMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CancelarMotorista))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CampoPesquisarMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PesquisarMotorista))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(403, 255));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void NomeMotoristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeMotoristaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeMotoristaActionPerformed

    private void EnviarMotoristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnviarMotoristaActionPerformed
      if(flag ==1 ){ 
       mod.setNomeMotorista(NomeMotorista.getText());
       mod.setTurno((String) TurnoMotorista.getSelectedItem());
       control.Salvar(mod);
       NomeMotorista.setEnabled(false);
       TurnoMotorista.setEnabled(false);
       CancelarMotorista.setEnabled(false);
       EnviarMotorista.setEnabled(false);
      }else{
          mod.setCodmotorista((Integer.parseInt(CodigoMotorista.getText())));
          mod.setNomeMotorista(NomeMotorista.getText());
          mod.setTurno((String) TurnoMotorista.getSelectedItem());
          control.Editar(mod);
          NomeMotorista.setEnabled(false);
          TurnoMotorista.setEnabled(false);
          CancelarMotorista.setEnabled(false);
          EnviarMotorista.setEnabled(false);
          
          CodigoMotorista.setText("");
          NomeMotorista.setText("");
          }
    }//GEN-LAST:event_EnviarMotoristaActionPerformed

    private void NovoMotoristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NovoMotoristaActionPerformed
        flag=1;
        NomeMotorista.setEnabled(true);
        TurnoMotorista.setEnabled(true);
        CancelarMotorista.setEnabled(true);
        EnviarMotorista.setEnabled(true);
    }//GEN-LAST:event_NovoMotoristaActionPerformed

    private void CampoPesquisarMotoristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoPesquisarMotoristaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoPesquisarMotoristaActionPerformed

    private void PesquisarMotoristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesquisarMotoristaActionPerformed
        mod.setPesquisa(CampoPesquisarMotorista.getText());
        ModeloMotorista model = control.BustaMotorista(mod);//chama modelo e enviar por parametro
        CodigoMotorista.setText(String.valueOf(model.getCodmotorista()));
        NomeMotorista.setText(model.getNomeMotorista());
        TurnoMotorista.setSelectedItem(model.getTurno());
        
        EditarMotorista.setEnabled(true);
        CancelarMotorista.setEnabled(true);
    }//GEN-LAST:event_PesquisarMotoristaActionPerformed

    private void CancelarMotoristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarMotoristaActionPerformed
        NomeMotorista.setEnabled(false);
        TurnoMotorista.setEnabled(false);
        CancelarMotorista.setEnabled(false);
        EnviarMotorista.setEnabled(false);
        NovoMotorista.setEnabled(true);
    }//GEN-LAST:event_CancelarMotoristaActionPerformed

    private void EditarMotoristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarMotoristaActionPerformed
        flag = 2;
        NomeMotorista.setEnabled(true);
        TurnoMotorista.setEnabled(true);
        CancelarMotorista.setEnabled(true);
        EnviarMotorista.setEnabled(true);
        EditarMotorista.setEnabled(false);
        
    }//GEN-LAST:event_EditarMotoristaActionPerformed

    private void CodigoMotoristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodigoMotoristaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CodigoMotoristaActionPerformed

    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMotorista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMotorista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMotorista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMotorista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMotorista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CampoPesquisarMotorista;
    private javax.swing.JButton CancelarMotorista;
    private javax.swing.JFormattedTextField CodigoMotorista;
    private javax.swing.JButton EditarMotorista;
    private javax.swing.JButton EnviarMotorista;
    private javax.swing.JFormattedTextField NomeMotorista;
    private javax.swing.JButton NovoMotorista;
    private javax.swing.JButton PesquisarMotorista;
    private javax.swing.JComboBox<String> TurnoMotorista;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
