/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Controle.ConexaoBD;
import Controller.Controle.ConexaoBus;
import Model.Modelo.ModeloBus;

/**
 *
 * @author MuAwa
 */
public class TelaBus extends javax.swing.JFrame {

    ModeloBus mod = new ModeloBus();
    ConexaoBD conex = new ConexaoBD();
    ConexaoBus control = new ConexaoBus();
    
    int flag = 0;
    
    public TelaBus() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        EditarBus = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        PesquisarBus = new javax.swing.JButton();
        NovoBus = new javax.swing.JButton();
        EnviarBus = new javax.swing.JButton();
        CancelarBus = new javax.swing.JButton();
        CodigoBus = new javax.swing.JTextField();
        PlacaBus = new javax.swing.JTextField();
        CampoPesquisar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        EditarBus.setText("Editar");
        EditarBus.setEnabled(false);
        EditarBus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarBusActionPerformed(evt);
            }
        });

        jLabel1.setText("Codigo: ");

        jLabel2.setText("Placa :  ");

        PesquisarBus.setText("Pesquisar");
        PesquisarBus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesquisarBusActionPerformed(evt);
            }
        });

        NovoBus.setText("Novo");
        NovoBus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NovoBusActionPerformed(evt);
            }
        });

        EnviarBus.setText("Enviar");
        EnviarBus.setEnabled(false);
        EnviarBus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnviarBusActionPerformed(evt);
            }
        });

        CancelarBus.setText("Cancelar");
        CancelarBus.setEnabled(false);
        CancelarBus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarBusActionPerformed(evt);
            }
        });

        CodigoBus.setEnabled(false);

        PlacaBus.setEnabled(false);
        PlacaBus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlacaBusActionPerformed(evt);
            }
        });

        CampoPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(CampoPesquisar)
                .addGap(18, 18, 18)
                .addComponent(PesquisarBus)
                .addGap(38, 38, 38))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(NovoBus, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(EnviarBus, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EditarBus, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CancelarBus))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CodigoBus, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PlacaBus, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CodigoBus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PlacaBus))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NovoBus)
                    .addComponent(EnviarBus)
                    .addComponent(EditarBus)
                    .addComponent(CancelarBus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CampoPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PesquisarBus))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(371, 238));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PlacaBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlacaBusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PlacaBusActionPerformed

    private void CampoPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoPesquisarActionPerformed

    private void NovoBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NovoBusActionPerformed
        flag=1;
        PlacaBus.setEnabled(true);
        CancelarBus.setEnabled(true);
        EnviarBus.setEnabled(true);
        
        CampoPesquisar.setText("");
        PlacaBus.setText("");
        CodigoBus.setText("");
    }//GEN-LAST:event_NovoBusActionPerformed

    private void EnviarBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnviarBusActionPerformed
       if(flag ==1 ){ 
       mod.setPlaca(PlacaBus.getText());
       control.Salvar(mod);
       PlacaBus.setEnabled(false);
       CancelarBus.setEnabled(false);
       EnviarBus.setEnabled(false);
       
       CampoPesquisar.setText("");
       CodigoBus.setText("");
       PlacaBus.setText("");  
      }else{
          mod.setCodbus((Integer.parseInt(CodigoBus.getText())));
          mod.setPlaca(PlacaBus.getText());          
          control.Editar(mod);
          PlacaBus.setEnabled(false);
          CancelarBus.setEnabled(false);
          EnviarBus.setEnabled(false);
          
          CampoPesquisar.setText("");
          CodigoBus.setText("");
          PlacaBus.setText("");    
          
      
      }
    }//GEN-LAST:event_EnviarBusActionPerformed

    private void EditarBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarBusActionPerformed
        flag = 2;
        PlacaBus.setEnabled(true);
        CancelarBus.setEnabled(true);
        EnviarBus.setEnabled(true);
        EditarBus.setEnabled(false);
    }//GEN-LAST:event_EditarBusActionPerformed

    private void CancelarBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarBusActionPerformed
        PlacaBus.setEnabled(false);
        CancelarBus.setEnabled(false);
        EnviarBus.setEnabled(false);
        NovoBus.setEnabled(true);
        EditarBus.setEnabled(false);
    }//GEN-LAST:event_CancelarBusActionPerformed

    private void PesquisarBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesquisarBusActionPerformed
       mod.setPesquisa(CampoPesquisar.getText());
        ModeloBus model = control.BustaBus(mod);//chama modelo e enviar por parametro
        CodigoBus.setText(String.valueOf(model.getCodbus()));
        PlacaBus.setText(model.getPlaca());
        
        
        EditarBus.setEnabled(true);
        CancelarBus.setEnabled(true);
    }//GEN-LAST:event_PesquisarBusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaBus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CampoPesquisar;
    private javax.swing.JButton CancelarBus;
    private javax.swing.JTextField CodigoBus;
    private javax.swing.JButton EditarBus;
    private javax.swing.JButton EnviarBus;
    private javax.swing.JButton NovoBus;
    private javax.swing.JButton PesquisarBus;
    private javax.swing.JTextField PlacaBus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
